# Generated by Django 4.0.4 on 2022-04-17 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('day2', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Draw_Image',
        ),
    ]
