# Generated by Django 4.0.4 on 2022-04-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='day1',
            field=models.BooleanField(default=False),
        ),
    ]
