# Generated by Django 4.0.4 on 2022-04-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_score_day1'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='day2',
            field=models.BooleanField(default=False),
        ),
    ]
