# Generated by Django 4.0.4 on 2022-04-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_score_day2'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='day3',
            field=models.BooleanField(default=False),
        ),
    ]
