# Generated by Django 4.0.4 on 2022-04-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_score_day3'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='d1_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='d2_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='score',
            name='d3_score',
            field=models.IntegerField(default=0),
        ),
    ]
